# Define variables that hold the versions of your dependencies and plugins.
# You use these variables in the subsequent blocks (the versions and plugins blocks).
[versions]
androidxActivityCompose = "1.8.2"
androidxComposeBom = "2023.10.01"
androidGradlePlugin = "8.2.0"
androidx-junit = "1.1.5"
appcompat = "1.6.1"
code-scanner = "16.0.0"
constraintlayout = "2.1.4"
core = "1.39.0"
core-ktx = "1.10.1"
databinding-runtime = "8.1.0"
datastore = "1.0.0"
espresso-core = "3.5.1"
google-protobuf = "0.9.1"
guava = "31.1-jre"
hilt-android = "2.48.1"
hilt-android-testing = "2.44.2"
hilt-navigation = "1.0.0"
junit = "4.13.2"
kotlin = "1.9.20"
kotlinx-coroutines-play-services = "1.6.4"
ktfmt = "0.12.0"
legacy-support-v4 = "1.0.0"
lifecycle-extensions = "2.2.0"
lifecycle-livedata-ktx = "2.6.1"
lifecycleRuntimeCompose = "2.7.0"
material = "1.10.0"
matter-android-demo-sdk = "1.0"
navigation-compose = "2.7.6"
navigation-fragment-ktx = "2.6.0"
play-services-base = "18.2.0"
play-services-home = "16.0.0"
play-services-threadnetwork = "16.0.0"
preference = "1.2.1"
protobuf-javalite = "3.18.0"
rules = "1.5.0"
runner = "1.5.2"
timber = "5.0.1"
uiautomator = "2.2.0"
zhanghai-compose-preference = "1.0.0"
zxing = "4.1.0"

# Dependencies
[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "code-scanner"}
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core = { module = "com.google.ar:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
databinding-runtime = { module = "androidx.databinding:databinding-runtime", version.ref = "databinding-runtime" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso-core" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso-core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt-android-testing" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }
# hilt-lifecycle-viewmodel = { module = "androidx.hilt:hilt-lifecycle-viewmodel", version.ref = "hilt-android" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines-play-services" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacy-support-v4" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-livedata-ktx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-livedata-ktx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
matter-android-demo-sdk = { module = "com.google.matter:matter-android-demo-sdk", version.ref = "matter-android-demo-sdk" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-fragment-ktx" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "play-services-base" }
play-services-home = { module = "com.google.android.gms:play-services-home", version.ref = "play-services-home" }
play-services-threadnetwork = { module = "com.google.android.gms:play-services-threadnetwork", version.ref = "play-services-threadnetwork" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf-javalite" }
rules = { module = "androidx.test:rules", version.ref = "rules" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
zxing = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing"}
zhanghai-compose-preference = { module = "me.zhanghai.compose.preference:library", version.ref = "zhanghai-compose-preference"}

# Plugins
[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
google-protobuf = { id = "com.google.protobuf", version.ref = "google-protobuf" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktfmt-plugin = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
